# Project Name
TARGET = main

USE_DAISYSP_LGPL=1
SD_CARD=1
USE_FATFS=1

# Sources
CPP_SOURCES = main.cpp WavFile.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

